# Generated by Django 3.2.5 on 2021-07-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(help_text='Enter hours', max_length=2)),
                ('minutes', models.IntegerField(help_text='Enter minutes', max_length=2)),
                ('result', models.BooleanField()),
            ],
        ),
    ]
