# Generated by Django 3.2.5 on 2021-07-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whattime', '0002_auto_20210702_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeCheck',
        ),
    ]
